### ISSUE TITLE
Any interest in reviving this package?

### ISSUE THREAD

**Issue by cjprybol** [malmaud/Pandas.jl#9]
Hi @malmaud,

The release version of this package fails to install on Julia 0.5
```julia
ERROR: LoadError: syntax: { } vector syntax is discontinued
 in include_from_node1(::String) at ./loading.jl:426
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:357
while loading /home/cjprybol/.julia/v0.5/Pandas/src/Pandas.jl, in expression starting on line 22
```

checking out master will allow it to install, but in Julia 0.4.6 and 0.5.0-rc2 the exported functions no longer work.
```julia
julia> read_csv()
ERROR: UndefVarError: read_csv not defined
julia> df = DataFrame([:age=>[27, 29, 27], :name=>["James", "Jill", "Jake"]])
ERROR: UndefVarError: DataFrame not defined
```

Given that this package hasn't been updated in over a year, I'm assuming that these errors are because this package uses defunct and deprecated functionality from older versions of Julia and PyCall. I tried to understand the source code to see if I could spot anything obvious, but the code is not commented and I'm not familiar enough with the PyCall syntax to deduce the logic from just the code itself.

I'm interested in working on getting this package to work with v0.5, and doing the updating, testing, and debugging to make that happen, but I'm not sure where to start. So I have a few questions:

1. Any ideas about what needs to be fixed, and how one might go about fixing them?
1. If no to the first, or if it would just be better to start from scratch, would you be interested in advising a re-write or contributing some tips about how to get started?
1. if no to the first and second, would you mind updating the readme of this package to mark it as deprecated?

**Comment by malmaud** [comment]
I'll look into it - this whole 'package' is just like 100 lines of code, so it should be pretty easy to get it working again.

**Comment by malmaud** [comment]
OK, the tagged version works in .5 now.

**Comment by cjprybol** [comment]
Thank you!
